# Generated by Django 3.0.8 on 2021-04-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawJsonCourse',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('json', models.TextField()),
            ],
        ),
    ]
