# Generated by Django 3.2.5 on 2022-01-28 02:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='RawJsonCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField()),
                ('api_id', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('sortable_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('short_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('sis_user_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('root_account', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('login_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(default=django.utils.timezone.now)),
                ('value', models.IntegerField(default=1)),
                ('note', models.CharField(blank=True, max_length=420, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvas.classsesh')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvas.user')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('account_id', models.BigIntegerField(null=True)),
                ('uuid', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('start_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('course_code', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('enrollment_term_id', models.BigIntegerField(null=True)),
                ('end_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('sis_course_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('rawjsoncourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvas.rawjsoncourse')),
            ],
        ),
        migrations.AddField(
            model_name='classsesh',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvas.course'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('inperson', 'In Person'), ('virtual', 'Virtual'), ('absent', 'Absent'), ('excused', 'Excused'), ('late', 'Late')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvas.classsesh')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvas.user')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('course_section_id', models.BigIntegerField(blank=True, default=None, null=True)),
                ('enrollment_state', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('role', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('role_id', models.BigIntegerField(blank=True, default=None, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_attended_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('total_activity_time', models.BigIntegerField(blank=True, default=None, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvas.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvas.user')),
            ],
            options={
                'unique_together': {('user', 'course', 'type')},
            },
        ),
    ]
