# Generated by Django 3.2.5 on 2022-02-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawjsoncourse',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
