# Generated by Django 3.0.8 on 2021-04-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('account_id', models.IntegerField()),
                ('uuid', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('start_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('course_code', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('end_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('sis_course_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
