# Generated by Django 3.0.8 on 2021-04-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0002_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='account_id',
            field=models.IntegerField(null=True),
        ),
    ]
