# Generated by Django 3.2.5 on 2022-03-24 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0003_alter_pull_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawjson',
            name='pull',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvas.pull'),
            preserve_default=False,
        ),
    ]
