# Generated by Django 3.0.8 on 2021-04-30 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0003_auto_20210430_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('sortable_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('short_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('sis_user_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('root_account', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('login_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('course_section_id', models.IntegerField(blank=True, default=None, null=True)),
                ('enrollment_state', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('roll', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('role_id', models.IntegerField(blank=True, default=None, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_attended_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('total_activity_time', models.IntegerField(blank=True, default=None, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvas.Course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvas.User')),
            ],
        ),
    ]
