# Generated by Django 3.2.5 on 2022-03-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0004_rawjson_pull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawjson',
            name='api_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='rawjson',
            unique_together={('api_id', 'pull', 'model')},
        ),
    ]
