# Generated by Django 3.0.8 on 2021-04-30 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0004_enrollment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='user_id',
            new_name='user',
        ),
    ]
