# Generated by Django 3.2.5 on 2022-04-01 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0005_auto_20220324_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualitativeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provenance', models.CharField(blank=True, choices=[(None, 'None'), ('IDEA', 'IDEA survey')], default=None, max_length=30)),
                ('text', models.TextField(max_length=16383)),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvas.course')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='canvas.user')),
            ],
        ),
    ]
