# Generated by Django 3.0.8 on 2021-04-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0008_auto_20210430_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_term_id',
            field=models.IntegerField(null=True),
        ),
    ]
