# Generated by Django 3.0.8 on 2021-05-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0009_course_enrollment_term_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='account_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='enrollment_term_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course_section_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='role_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='total_activity_time',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
