# Generated by Django 3.2.5 on 2022-01-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0011_course_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawjsoncourse',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
