# Generated by Django 3.2.5 on 2022-01-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0012_alter_rawjsoncourse_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawjsoncourse',
            name='api_id',
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
