# Generated by Django 3.2.5 on 2022-01-08 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0013_rawjsoncourse_api_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='api_id',
        ),
        migrations.AddField(
            model_name='course',
            name='rawjsoncourse',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='canvas.rawjsoncourse'),
            preserve_default=False,
        ),
    ]
