# Generated by Django 3.2.5 on 2022-01-27 07:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0014_auto_20220108_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSesh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvas.course')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(default=django.utils.timezone.now)),
                ('value', models.IntegerField(default=1)),
                ('note', models.CharField(blank=True, max_length=420, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvas.classsesh')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvas.user')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('inperson', 'In Person'), ('virtual', 'Virtual'), ('absent', 'Absent'), ('excused', 'Excused'), ('late', 'Late')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvas.classsesh')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvas.user')),
            ],
        ),
    ]
